name: BootCamp 2023

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy using Surge
        run: surge ./BootCamp2023_s.surge.sh --token ${{ secrets.SURGE_TOKEN }}
